[package]
name = "rterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
eframe = "0.25.0"
egui = "0.25.0"
env_logger = "0.11.1"
log = "0.4.20"
nix = {version = "0.27.1", features = ["process", "term", "fs"]}
